import { ReactNode, useContext, useMemo } from "react";
import Head from "next/head";
import Image from "next/image";
import { Slide1, Slide2, Slide3 } from "components/Slides";
import Sidebar from "components/Sidebar";
import TransitionWrapper from "components/TransitionWrapper";
import context, { TContext } from "context";

export interface TComponent {
  Component: Function;
  id: number;
}

const componentMap: TComponent[] = [
  { Component: Slide1 },
  { Component: Slide2 },
  { Component: Slide3 },
].map((o: any, id: number): TComponent => Object.assign(o, { id }));

const Home = (): ReactNode => {
  const { currentSlide } = useContext<TContext>(context);

  const children = useMemo((): ReactNode[] => componentMap.map(
    ({ Component, id }: TComponent): ReactNode => (
      <TransitionWrapper key={id} inProp={id === currentSlide}>
        <Component inProp={id === currentSlide} />
      </TransitionWrapper>
    )
  ), [currentSlide]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Sidebar />
      {children}
    </>
  );
};

export default Home;
