import { ReactNode, useContext, useMemo } from "react";
import Head from "next/head";
import Sidebar from "components/Sidebar";
import TransitionWrapper from "components/TransitionWrapper";
import context, { TContext, TComponent } from "context";

const Home = (): ReactNode => {
  const { currentSlide, currentStack } = useContext<TContext>(context);

  const children = useMemo((): ReactNode[] => currentStack.map(
    ({ Component, id }: TComponent): ReactNode => (
      <TransitionWrapper key={id} inProp={id === currentSlide}>
        <Component inProp={id === currentSlide} />
      </TransitionWrapper>
    )
  ), [currentSlide, currentStack]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Sidebar />
      {children}
    </>
  );
};

export default Home;
