import { ReactNode, useContext } from "react";
import Head from "next/head";
import Image from "next/image";
import { Slide1, Slide2, Slide3 } from "components/Slides";
import context, { TContext } from "context";

import Sidebar from "components/Sidebar";
import TransitionWrapper from "components/TransitionWrapper";

const componentMap: any[] = [
  { Component: Slide1 },
  { Component: Slide2 },
  { Component: Slide3 },
].map((o, id) => Object.assign(o, { id }));

const Home = (): ReactNode => {
  const { setCurrentSlide, currentSlide } = useContext<TContext>(context);

  const children = componentMap.map(({ Component, id }) => (
    <TransitionWrapper key={id} inProp={id === currentSlide}>
      <Component inProp={id === currentSlide} />
    </TransitionWrapper>
  ));

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Sidebar />
      {children}
    </>
  );
};

export default Home;
